name: CI

on:
  push:
    paths: 
      - '**.js'
      - '!docs/**'
      - '**.yml'
  pull-request:
    types:
      - opened
      - closed
      - synchronize
      - labeled
      - unlabeled
    branches: [ 0.5/CCVMTPTPM ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: |
        echo Hello World!!!
        echo "TODAY=$(date +'%y-%m-%d')" >> GITHUB_ENV
    - name: Run a multi-line script
      run: |
        echo Add another action to build
        echo test, and deploy your project
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
      working-directory: ./client
    - name: Build and test
      run: |
        npm start
        npm run build
        npm test
      working-directory: ./client
    